apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ror2" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: ror2-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: ror2-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: game-udp
      port: {{ .Values.server.port }}
      targetPort: game-udp
      protocol: UDP
{{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
